### PR TITLE
fix windows build and update build script to reuse cmake

### LINKED ISSUE #9: Why not CMake for gns-sys build?
For context, I'm working on a pull request to fix building for Windows, since building gns-sys for Windows is just completely broken. (missing some Windows-specific .c files from upstream, wrong names for libs, etc).

Looking at upstream, GNS uses [CMake](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/BUILDING.md#building-1) for its build process. While I haven't delved into trying to use it yet, it appears there is a [Rust build dependency for CMake](https://docs.rs/cmake/latest/cmake/), and I'm curious if there are any reasons that the current `cc` build dependency is used instead? Manually specifying the build process in [build.rs](https://github.com/hussein-aitlahcen/gns-rs/blob/master/gns-sys/build.rs#L62-L124) makes it extremely easy to get out of sync, as seen by the above issues with building for Windows. Even worse, upstream already has the appropriate configuration to deal with different platform building, so fixing Windows builds in gns-sys would be duplicating some of that per-platform logic.

tl;dr: Any reason that upstream GNS is compiled with cc in gns-sys, and not CMake? If not, is it alright if I go ahead and make a pull request to switch to CMake?

### PR DESCRIPTION
**Pull request by hussein-aitlahcen**
closes #9

### CODE REVIEW

**Comment by hussein-aitlahcen** [comment]
> I see the latest changes are trying to use vcpkg on Windows. afaik, GameNetworkingSockets _itself_ is also in vcpkg, so it might be worth using e.g. https://crates.io/crates/vcpkg to simply pull in the vcpkg built version of GameNetworkingSockets on Windows, instead of trying to build it via cmake at all.

I can see the presence of gns but it's using 1.4.1 which is pretty old: https://github.com/microsoft/vcpkg/blob/master/ports/gamenetworkingsockets/vcpkg.json

If we can patch to get the version we are pinned against that would be nifty!

File: gns-sys/build.rs [hunk 1]
```diff
@@ -1,14 +1,152 @@
...
+            .status()
+            .is_ok()
+        {
+            Command::new("thirdparty/GameNetworkingSockets/vcpkg/bootstrap-vcpkg.bat").status().unwrap();
+        }
+        Command::new("thirdparty/GameNetworkingSockets/vcpkg/vcpkg")
+            .args(&[
+                "install",
+                "--x-manifest-root=thirdparty/GameNetworkingSockets",
+                "--tripler=x64-windows-static",
```
Comment (debroejm) [inline gns-sys/build.rs:126]: typo: `--tripler` should be `--triplet`

Also you probably want to use `x64-windows-static-md`. `x64-windows-static` also builds the CRT statically, which is probably not what you want to do. (Note that if you _did_ want to do that, you would also need to add `c.define("MSVC_CRT_STATIC", "ON");`)

Comment (hussein-aitlahcen) [reply gns-sys/build.rs]: fixed!

**Comment by hussein-aitlahcen** [comment]
@debroejm I think I'm close to having it working. I have a discrepancy in abseil linking because we use a newer version in linux. Currently avoiding linking with part of the lib not available on the older version https://github.com/ValveSoftware/GameNetworkingSockets/blob/725e273c7442bac7a8bc903c0b210b1c15c34d92/.gitmodules#L4.

File: gns-sys/build.rs [hunk 2]
```diff
@@ -1,14 +1,164 @@
...
+    link("static=absl_log_internal_check_op");
+    link("static=absl_random_seed_gen_exception");
+    link("static=absl_exponential_biased");
+    link("static=absl_log_internal_conditions");
+    link("static=absl_random_seed_sequences");
+    link("GameNetworkingSockets_s");
+
+    let mut c = cmake::Config::new("thirdparty/GameNetworkingSockets");
+
+    if cfg!(target_os = "windows") {
```
Comment (debroejm) [inline gns-sys/build.rs:112]: This should probably check for MSVC toolchain as well, similar to https://github.com/hussein-aitlahcen/gns-rs/pull/11/files#diff-a8b434991a9b95ad5b6ab9e9c253e131e96e8384c4e6ea262a25090827e4c44dR26.

iirc, I think MinGW builds very similarly to Linux builds, even on Windows.

File: gns-sys/build.rs [hunk 3]
```diff
@@ -1,14 +1,164 @@
...
+    } else {
+        link("static=protobuf");
+        link("static=crypto");
+        link("static=ssl");
+        link("stdc++");
+    }
+
+    c.static_crt(false);
+    c.define("BUILD_STATIC_LIB", "ON");
+    c.define("BUILD_SHATED_LIB", "OFF");
```
Comment (debroejm) [inline gns-sys/build.rs:158]: typo: This should be `BUILD_SHARED_LIB`

**Comment by debroejm** [comment]
I tried to checkout and build locally, but I'm getting a bunch of build errors like:
```
...\gns-sys\thirdparty\GameNetworkingSockets\src\common\steamnetworkingsockets_messages_certs.pb.h(16,1): error C1189: #error:  "Protobuf C++ gencode is built with an incompatible version of" ...
```
This might be an issue with my locally installed protobuf conflicting with things though.

Overall, patches look good to me aside from a few nits. I don't like the fact that there are almost 100 abseil dependencies specified, as that seems very prone to breaking, but if it works for now, it works. I want to see about automatically pulling those dependencies from the GNS build somehow, but that can be done as follow-up (I have a few ideas).
